#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

displayselect
xrandr --dpi 105		# Set DPI. User may want to use a larger number for larger screens.
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
redshift -O 5000  # warm colors for the background.


autostart="mpd mypicom dunst unclutter pipewire remaps"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# Load nvidia-settings.
nvidia-settings --load-config-only
